src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Classe représentant une image associée à une figure.
 */
#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    /**
     * Identifiant unique de l'image.
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * URL de l'image.
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(
        message: "L'URL de l'image est obligatoire.",
        allowNull: true,
        groups: ['Default']
    )]
    #[Assert\Url(
        message: "L'URL de l'image doit être valide.",
        protocols: ['http', 'https'],
        groups: ['Default']
    )]
    private ?string $url = null;

    /**
     * Texte alternatif de l'image.
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(
        max: 255,
        maxMessage: 'Le texte alternatif ne doit pas dépasser {{ limit }} caractères.'
    )]
    private ?string $altText = null;

    /**
     * Date de création de l'image.
     */
    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    /**
     * Figure associée à l'image.
     */
    #[ORM\ManyToOne(targetEntity: Figure::class, inversedBy: 'images', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Figure $figure = null;


    /**
     * Constructeur de la classe Image.
     * Initialise la date de création.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }// end __construct()


    /**
     * Récupère l'identifiant unique de l'image.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }// end getId()


    /**
     * Récupère l'URL de l'image.
     *
     * @return string|null
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }// end getUrl()


    /**
     * Définit l'URL de l'image.
     *
     * @param string $url URL de l'image
     *
     * @return $this
     */
    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }// end setUrl()


    /**
     * Récupère le texte alternatif de l'image.
     *
     * @return string|null
     */
    public function getAltText(): ?string
    {
        return $this->altText;
    }// end getAltText()


    /**
     * Définit le texte alternatif de l'image.
     *
     * @param string|null $altText texte alternatif
     *
     * @return $this
     */
    public function setAltText(?string $altText): static
    {
        $this->altText = $altText;

        return $this;
    }// end setAltText()


    /**
     * Récupère la date de création de l'image.
     *
     * @return \DateTimeImmutable|null
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }// end getCreatedAt()


    /**
     * Récupère la figure associée à l'image.
     *
     * @return Figure|null
     */
    public function getFigure(): ?Figure
    {
        return $this->figure;
    }// end getFigure()


    /**
     * Définit la figure associée à l'image.
     *
     * @param Figure|null $figure figure associée
     *
     * @return $this
     */
    public function setFigure(?Figure $figure): static
    {
        $this->figure = $figure;

        return $this;
    }// end setFigure()


    /**
     * Retourne l'auteur de la figure associée à l'image.
     *
     * @return user L'utilisateur qui a créé la figure
     */
    public function getAuthor(): User
    {
        return $this->figure->getAuthor();
    }


    /**
     * Convertit l'objet Image en chaîne de caractères.
     * Retourne l'URL de l'image ou 'Image' si l'URL est null.
     *
     * @return string
     */
    public function __toString(): string
    {
        return $this->url ?? 'Image';
    }// end __toString()


}// end class

src/Form/FigureType.php
<?php

namespace App\Form;

use App\Entity\Figure;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FigureType extends AbstractType
{


    /**
     * Construit le formulaire pour une figure.
     *
     * Définit les champs du formulaire de création/modification d'une figure.
     *
     * @param FormBuilderInterface $builder constructeur du formulaire
     * @param array                $options options du formulaire
     *
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'name',
                TextType::class,
                [
                    'label' => 'Nom de la figure',
                    'attr'  => [
                        'placeholder' => 'Entrez le nom de la figure',
                    ],
                ]
            )
            ->add(
                'description',
                TextareaType::class,
                [
                    'label' => 'Description',
                    'attr'  => [
                        'placeholder' => 'Décrivez la figure',
                    ],
                ]
            )
            ->add(
                'figureGroup',
                ChoiceType::class,
                [
                    'label'       => 'Groupe de Figures', // Supprime le label au-dessus du champ
                    'choices'     => [
                        'Grabs'              => 'grabs',
                        'Rotations'          => 'rotations',
                        'Flips'              => 'flips',
                        'Rotations Désaxées' => 'rotations_desaxees',
                        'Slides'             => 'slides',
                        'One Foot Tricks'    => 'one_foot_tricks',
                        'Old School'         => 'old_school',
                    ],
                    'placeholder' => 'Sélectionnez un groupe',
                    'empty_data'  => '', // Pour éviter qu'une valeur vide pose problème
                    'required'    => true,
                ]
            );

    }


    /**
     * Configure les options du formulaire.
     *
     * Associe le formulaire à l'entité Figure.
     *
     * @param OptionsResolver $resolver résolveur des options
     *
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => Figure::class,
            ]
        );
    }


}

src/Controller/FigureController.php
<?php

namespace App\Controller;

use App\Entity\Figure;
use App\Form\CommentType;
use App\Form\FigureType;
use App\Form\ImageType;
use App\Form\MainImageType;
use App\Form\VideoType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class FigureController extends AbstractController
{


    /**
     * Gère la création ou la modification d’une figure.
     *
     * @param Request                $request La requête HTTP contenant le formulaire
     * @param EntityManagerInterface $em      Le gestionnaire Doctrine pour la persistance
     * @param SluggerInterface       $slugger Le service utilisé pour générer les slugs
     * @param Figure|null            $figure  La figure à modifier (null en création)
     *
     * @return Response La réponse HTML partielle (AJAX) ou complète (page d'édition)
     */
    #[Route('/figure/add', name: 'app_figure_add', methods: ['GET', 'POST'])]
    #[Route('/figure/{slug}/edit', name: 'app_figure_edit', methods: ['GET', 'POST'])]
    public function editFigure(Request $request, EntityManagerInterface $em, SluggerInterface $slugger, ?Figure $figure = null): Response
    {
        $isEdit = $this->isEditMode($figure);
        $figure = $this->initializeFigure($figure);

        $form = $this->createForm(FigureType::class, $figure);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($this->isDuplicateFigureName($em, $figure)) {
                return $this->render('partials/_create_figure_form.html.twig', [
                    'createFigureForm' => $form->createView(),
                ]);
            }

            if ($form->isValid()) {
                $this->saveFigure($em, $figure, $slugger);

                return new Response('<div id="create-figure-success" data-redirect="'.$this->generateUrl('app_figure_detail', ['slug' => $figure->getSlug()]).'"></div>');
            }

            return $this->render('partials/_create_figure_form.html.twig', [
                'createFigureForm' => $form->createView(),
            ]);
        }

        // Formulaires secondaires (uniquement en édition)
        return $this->render(
            $isEdit ? 'figure/edit.html.twig' : 'home/index.html.twig',
            [
                'form'             => $form->createView(),
                'figure'           => $figure,
                'mainImageForm'    => $isEdit ? $this->createForm(MainImageType::class, null, ['figure' => $figure])->createView() : null,
                'imageForms'       => $isEdit ? $this->generateImageForms($figure) : [],
                'videoForms'       => $isEdit ? $this->generateVideoForms($figure) : [],
                'editMode'         => $isEdit,
            ]
        );
    }


    #[Route('/figure/delete/{id}', name: 'app_figure_delete', methods: ['POST'])]
    public function delete(Figure $figure, Request $request, EntityManagerInterface $em): RedirectResponse
    {
        $this->denyAccessUnlessGranted('FIGURE_DELETE', $figure);

        if ($this->isCsrfTokenValid('delete_figure_'.$figure->getId(), $request->request->get('_token'))) {
            if ($figure->getMainImage()) {
                $figure->setMainImage(null);
                $em->flush();
            }

            $em->remove($figure);
            $em->flush();

            $this->addFlash('success', 'Figure supprimée avec succès.');
        } else {
            $this->addFlash('error', 'Erreur de sécurité : impossible de supprimer la figure.');
        }

        return $this->redirectToRoute('app_home');
    }


    #[Route('/figure/{slug}', name: 'app_figure_detail', methods: ['GET'])]
    public function detail(EntityManagerInterface $em, string $slug, CommentRepository $commentRepository, Request $request): Response
    {
        $figure = $em->getRepository(Figure::class)->findOneBy(['slug' => $slug]);

        if (!$figure) {
            throw $this->createNotFoundException("Figure introuvable pour le slug : $slug");
        }

        $mainImageForm = $this->createForm(MainImageType::class, null, ['figure' => $figure]);
        $commentsData = $commentRepository->findByFigureWithPagination($figure?->getId(), $request->query->getInt('page', 1), 10);

        return $this->render('figure/detail.html.twig', [
            'figure'        => $figure,
            'comments'      => $commentsData['items'] ?? [],
            'currentPage'   => $commentsData['currentPage'] ?? 1,
            'lastPage'      => $commentsData['lastPage'] ?? 1,
            'imageForm'     => $this->createForm(ImageType::class)->createView(),
            'videoForm'     => $this->createForm(VideoType::class)->createView(),
            'commentForm'   => $this->createForm(CommentType::class)->createView(),
            'mainImageForm' => $mainImageForm->createView(),
        ]);
    }


    // ----------------------
    // Helpers privés
    // ----------------------

    private function isEditMode(?Figure $figure): bool
    {
        return $figure && $figure->getId();
    }


    private function initializeFigure(?Figure $figure): Figure
    {
        if (!$figure) {
            $figure = new Figure();
            $figure->setAuthor($this->getUser());
        } else {
            $this->denyAccessUnlessGranted('FIGURE_EDIT', $figure);
        }

        return $figure;
    }


    private function isDuplicateFigureName(EntityManagerInterface $em, Figure $figure): bool
    {
        $existingFigure = $em->getRepository(Figure::class)->findOneBy(['name' => $figure->getName()]);

        return $existingFigure && (!$figure->getId() || $existingFigure->getId() !== $figure->getId());
    }


    private function saveFigure(EntityManagerInterface $em, Figure $figure, SluggerInterface $slugger): void
    {
        if (!$figure->getSlug()) {
            $figure->generateSlug($slugger);
        }

        $em->persist($figure);
        $em->flush();
    }


    private function generateImageForms(Figure $figure): array
    {
        $forms = [];
        foreach ($figure->getImages() as $img) {
            $forms[$img->getId()] = $this->createForm(ImageType::class, $img)->createView();
        }

        return $forms;
    }


    private function generateVideoForms(Figure $figure): array
    {
        $forms = [];
        foreach ($figure->getVideos() as $vid) {
            $forms[$vid->getId()] = $this->createForm(VideoType::class, $vid)->createView();
        }

        return $forms;
    }


}

templates/figure/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ figure.name }}
	- Détails
{% endblock %}

{% block body %}
	<section
		class="container my-5">

		<!-- Image principale avec ombre -->
		<div class="position-relative text-center shadow-lg rounded">
			{% include "partials/_main_image.html.twig" %}

			<!-- Nom de la figure en superposition -->
			<h1 class="position-absolute top-50 start-50 translate-middle text-white bg-dark bg-opacity-75 px-3 py-2 rounded">
				{{ figure.name }}
			</h1>

			<!-- Boutons Modifier/Supprimer image principale -->
			{% include "partials/_main_image_buttons.html.twig" %}
		</div>

		<!-- Modales pour la modification et la suppression de l’image principale -->
		{% include "partials/_edit_main_image_modal.html.twig" with { editMode: true } %}
		{% include "partials/_delete_main_image_modal.html.twig" with { editMode: true } %}

		<!-- Section Images et Vidéos -->
		<!-- Bouton d'affichage des médias sur mobile -->
			<button class="btn btn-neutral d-md-none w-100 mx-auto my-3" type="button" data-bs-toggle="collapse" data-bs-target="#mediaCollapse" aria-expanded="false" aria-controls="mediaCollapse"> Voir les médias
		</button>

		<div id="mediaCollapse" class="collapse my-5 p-4 bg-light rounded shadow-lg text-center">
			<h5 class="text-uppercase mb-4">Images & Vidéos</h5>

			<div
				class="row justify-content-center">
				{# Affichage des images en premier #}
				{% for image in figure.images %}
					<div class="col-md-3 col-sm-6 mb-3">
						<div class="card shadow-lg border-0">
							<img src="{{ asset(image.url) }}" class="card-img-top rounded" alt="{{ image.altText|default('Image supplémentaire') }}" style="object-fit: cover; height: 200px; width: 100%;">
						</div>
					</div>
				{% endfor %}

				{# Carte d'ajout d'image si utilisateur autorisé #}
				{% if is_granted('ROLE_USER') and figure.author == app.user %}
					<div class="col-md-3 col-sm-6 mb-3">
						<div class="card card-bg-blur shadow-lg d-flex align-items-center justify-content-center" style="height: 200px;" data-bs-toggle="modal" data-bs-target="#addImageModal">
							<div class="card-body d-flex align-items-center justify-content-center">
								<i class="fa-regular fa-square-plus fa-3x" style="color: #ffffff;"></i>
							</div>
						</div>
					</div>
				{% endif %}

				{# Affichage des vidéos ensuite #}
				{% for video in figure.videos %}
					<div class="col-md-3 col-sm-6 mb-3">
						<div
							class="card shadow-lg border-0" style="height: 200px; overflow: hidden;">
							<!-- Conteneur 'video-wrapper' en position relative, occupant 100%/100% -->
							<div class="video-wrapper" style="
									            position: relative;
									            width: 100%;
									            height: 100%;
									        ">
								{{ video.embedCode|raw }}
							</div>
						</div>
					</div>
				{% endfor %}

				{# Carte d'ajout de vidéo si utilisateur autorisé #}
				{% if is_granted('ROLE_USER') and figure.author == app.user %}
					<div class="col-md-3 col-sm-6 mb-3">
						<div class="card card-bg-blur shadow-lg d-flex align-items-center justify-content-center" style="height: 200px;" data-bs-toggle="modal" data-bs-target="#addVideoModal">
							<div class="card-body d-flex align-items-center justify-content-center">
								<i class="fa-regular fa-square-plus fa-3x" style="color: #ffffff;"></i>
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>


		<!-- Modale pour ajouter une image -->
		<div class="modal fade" id="addImageModal" tabindex="-1" aria-labelledby="addImageModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content text-center shadow-lg">
					<div class="modal-header">
						<h5 class="modal-title text-uppercase" id="addImageModalLabel">Ajouter une image</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						{{ form_start(imageForm, {
                    'action': path('app_figure_add_image', { figureId: figure.id }),
                    'method': 'POST',
                    'attr': { 'enctype': 'multipart/form-data' }
                }) }}

						<div class="mb-3">
							{{ form_label(imageForm.file, null, { 'label_attr': {'class': 'form-label d-block mb-2'} }) }}
							{{ form_widget(imageForm.file, {'attr': {'class': 'form-control'}}) }}
						</div>

						<div class="d-grid">
							<button type="submit" class="btn btn-figure-submit">Ajouter</button>
						</div>

						{{ form_end(imageForm) }}
					</div>
				</div>
			</div>
		</div>

		<!-- Modale pour ajouter une vidéo -->
		<div class="modal fade" id="addVideoModal" tabindex="-1" aria-labelledby="addVideoModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content text-center shadow-lg">
					<div class="modal-header">
						<h5 class="modal-title text-uppercase" id="addVideoModalLabel">Ajouter une vidéo</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						{{ form_start(videoForm, {
                    'action': path('app_figure_add_video', { figureId: figure.id }),
                    'method': 'POST'
                }) }}
						<div class="mb-3">
							{{ form_label(videoForm.embedCode, null, { 'label_attr': {'class': 'form-label d-block mb-2'} }) }}
							{{ form_widget(videoForm.embedCode, {'attr': {'class': 'form-control'}}) }}
						</div>
						<div class="d-grid mt-3">
							<button type="submit" class="btn btn-figure-submit">Ajouter</button>
						</div>
						{{ form_end(videoForm) }}
					</div>
				</div>
			</div>
		</div>

		<!-- Description -->
		<div class="my-5 p-4 bg-light rounded shadow-lg text-center position-relative">
			{% if is_granted('ROLE_USER') and figure.author == app.user %}
				<!-- Bouton EDIT en haut à droite -->
				<a href="{{ path('app_figure_edit', { slug: figure.slug }) }}" class="btn btn-secondary btn-sm position-absolute top-0 end-0 mt-2 me-2" data-bs-toggle="tooltip" title="Modifier la figure">
					<i class="fa-solid fa-pen"></i>
				</a>
			{% endif %}

			<h5 class="text-uppercase">Détails de la figure</h5>
			<p>{{ figure.description }}</p>

			<!-- Informations importantes sous forme de badges -->
			<div class="d-flex justify-content-center flex-wrap gap-2 mt-4">
				<span class="badge badge-info">
					Créée le :
					{{ figure.createdAt|date('d/m/Y') }}
				</span>
				{% if figure.updatedAt %}
					<span class="badge badge-warning">
						Modifiée le :
						{{ figure.updatedAt|date('d/m/Y') }}
					</span>
				{% endif %}
				<span class="badge badge-secondary">
					Groupe :
					{{ figure.figureGroup }}
				</span>
				<span class="badge badge-success">
					Auteur :
					{{ figure.author.username }}
				</span>
			</div>
		</div>


		<!-- Section des commentaires -->
		<div
			class="mt-5">
			<!-- Formulaire pour ajouter un commentaire -->
			{% if is_granted('ROLE_USER') %}
				<div class="mt-4 p-4 bg-light rounded shadow-lg text-center">
					<h5 class="text-uppercase">Ajouter un commentaire</h5>
					{{ form_start(commentForm, {
                'action': path('app_figure_add_comment', { 'id': figure.id }),
                'method': 'POST',
                'attr' : {'class': 'mx-auto', 'style': 'max-width: 600px;'}
            }) }}
					{{ form_widget(commentForm.content, {'label': false, 'attr' : { 'class': 'form-control', 'rows': 3, 'placeholder': 'Ecrivez votre commentaire ici...' } }) }}
					<div class="d-grid mt-3">
						<button type="submit" class="btn btn-comment-submit">Publier</button>
					</div>
					{{ form_end(commentForm) }}
				</div>
			{% endif %}

			<div class="my-5 p-4 bg-light rounded shadow-lg text-center">
				<h5 class="text-uppercase text-center">Commentaires</h5>

				{% if comments is not empty %}
					<div class="comments-container my-4">
						{% for comment in comments %}
							<div class="comment-box p-3 mb-3 rounded shadow-lg {% if comment.author == figure.author %}comment-author{% endif %}">
								<div class="comment-content">
									<div class="d-flex align-items-center mb-2">
										<strong class="comment-username {% if comment.author == figure.author %}{% endif %}">
											{{ comment.author.username }}
										</strong>
										<small class="text-muted ms-3">{{ comment.createdAt|date('d/m/Y H:i') }}</small>
									</div>
									<p class="comment-text">{{ comment.content }}</p>
								</div>
							</div>
						{% endfor %}
					</div>

					<!-- Pagination -->
					<nav aria-label="Pagination" class="mt-4">
						<ul class="pagination justify-content-center">
							{% if currentPage > 1 %}
								<li class="page-item">
									<a class="page-link" href="{{ path('app_figure_detail', { slug: figure.slug, page: currentPage - 1 }) }}">
										Précédent
									</a>
								</li>
							{% endif %}
							{% for i in 1..lastPage %}
								<li class="page-item {% if i == currentPage %}active{% endif %}">
									<a class="page-link" href="{{ path('app_figure_detail', { slug: figure.slug, page: i }) }}">
										{{ i }}
									</a>
								</li>
							{% endfor %}
							{% if currentPage < lastPage %}
								<li class="page-item">
									<a class="page-link" href="{{ path('app_figure_detail', { slug: figure.slug, page: currentPage + 1 }) }}">
										Suivant
									</a>
								</li>
							{% endif %}
						</ul>
					</nav>
				{% else %}
					<p class="text-muted">Aucun commentaire disponible pour cette figure.</p>
				{% endif %}
			</div>
		</div>
	</section>
{% endblock %}